<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'taWztbfWwOA=');
$cfg_Cs[2]=array(0,1,1,'xu/Q0Newsbg=');
$cfg_Cs[3]=array(0,1,1,'taWztcn6u+4=');
$cfg_Cs[4]=array(0,1,1,'0NDStdfK0bY=');
$cfg_Cs[5]=array(1,1,1,'y8C3ybO1');
$cfg_Cs[6]=array(1,1,1,'uLS5xcbv0NA=');
$cfg_Cs[7]=array(1,1,1,'uavCt7O1');
$cfg_Cs[8]=array(1,1,1,'yb212LO1');
$cfg_Cs[9]=array(1,1,1,'1du1/i/Qob62s7U=');
$cfg_Cs[10]=array(1,1,1,'Qk1Y');
$cfg_Cs[11]=array(1,1,1,'s8fK0LO1vLDG5Mv7');
$cfg_Cs[12]=array(2,1,1,'s7XJ7dewsbg=');
$cfg_Cs[13]=array(2,1,1,'yMvJ7dewsbg=');
?>