<div style="float: left; width: 343px; height: 293px; background-color: #ffffff;
                border: solid 1px #ccc; margin-left: 15px;margin-top: 15px;">
                <div style="background-color: #cccccc; width: 313px; height: 188px; margin-top: 16px;
                    margin-left: 14px;">
                    <a target="_blank" href="[field:arcurl/]"><img src="[field:litpic/]" alt="[field:fulltitle/]" height="188" width="313"></a>
                </div>
                <div style="margin-left: 14px; line-height: 25px; margin-top: 10px;">
                    <div style="font-size: 12px;color:#cccccc;">[field:pubdate function="MyDate('YƒÍm‘¬d»’',@me)"/]</div>
                    <div style="font-size: 14px;height:45px;">
                       <a target="_blank" href="[field:arcurl/]">[field:fulltitle/]</a></div>
                    
                </div>
            </div>