<li style="border-bottom:dashed 1px #ccc;height:70px; margin-bottom:15px;">
<div style="float:left;width:85px;height:55px; overflow:hidden;"><a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" width="83" title="[field:fulltitle/]" /></a></div>
<div style="float:right;width:145px;height:52px; overflow:hidden;"><a href="[field:arcurl/]" target="_blank" title="[field:fulltitle/]">[field:title/]</a></div>
</li>