<?php
$z[0]=Array("arcurl","",134,149);
$z[1]=Array("fulltitle","",158,176);
$z[2]=Array("litpic","",226,241);
$z[3]=Array("fulltitle","",248,266);
$z[4]=Array("arcurl","",504,519);
$z[5]=Array("fulltitle","",528,546);
$z[6]=Array("fulltitle","",548,566);
$z[7]=Array("pubdate","",662,713);
$z[7][4]['function']="MyDate('YÄêmÔÂdÈÕ',@me)";
$z[8]=Array("description","",876,896);
$z[9]=Array("arcurl","",1032,1047);
$z[10]=Array("goodpost","",1152,1169);
$z[11]=Array("goodpost","",1225,1242);
$z[12]=Array("click","",1278,1292);
$z[13]=Array("click","",1371,1385);

?>