<div class="xh_post_h_3 ofh">
                            <div class="xh">
                                <a target="_blank" href="[field:arcurl/]" title="[field:fulltitle/]">
                                    <img src="[field:litpic/]" alt="[field:fulltitle/]" height="240" width="400"></a></div>
                            <div class="r ofh">
                                <h2 class="xh_post_h_3_title ofh" style="height:60px;">
                                    <a target="_blank" href="[field:arcurl/]" title="[field:fulltitle/]">[field:fulltitle/]</a>
                                </h2>
                                <span class="time">[field:pubdate function="MyDate('Y年m月d日',@me)"/]</span>
                                <div class="xh_post_h_3_entry ofh" style="color:#555;height:80px; overflow:hidden;">
                                    [field:description/]
                                </div>
                                <div class="b">
                                    <a href="[field:arcurl/]" class="xh_readmore" rel="nofollow">read
                                        more</a> <span title="[field:goodpost/]人赞" class="xh_love"><span class="textcontainer"><span>[field:goodpost/]</span></span> </span> <span title="[field:click/]人浏览" class="xh_views">
                                                    [field:click/]</span>
                                </div>
                            </div>
                        </div>