<?php
$z[0]=Array("arcurl","",142,157);
$z[1]=Array("fulltitle","",166,184);
$z[2]=Array("litpic","",234,249);
$z[3]=Array("fulltitle","",256,274);
$z[4]=Array("arcurl","",491,506);
$z[5]=Array("fulltitle","",515,533);
$z[6]=Array("fulltitle","",535,553);
$z[7]=Array("pubdate","",649,704);
$z[7][4]['function']="MyDate('YÄêmÔÂdÈÕ H:i',@me)";
$z[8]=Array("description","",780,800);
$z[9]=Array("goodpost","",907,924);
$z[10]=Array("goodpost","",980,997);
$z[11]=Array("click","",1062,1076);
$z[12]=Array("click","",1101,1115);
$z[13]=Array("typeurl","",1255,1271);
$z[14]=Array("typename","",1285,1302);
$z[15]=Array("typename","",1369,1386);

?>