<div class="xh_post_h_3 ofh">
                            <div class="xh_265x265">
                                <a target="_blank" href="[field:arcurl/]" title="[field:fulltitle/]">
                                    <img src="[field:litpic/]" alt="[field:fulltitle/]" height="240" width="400"></a></div>
                            <div class="r ofh">
                                <h2 class="xh_post_h_3_title ofh">
                                    <a target="_blank" href="[field:arcurl/]" title="[field:fulltitle/]">[field:fulltitle/]</a>
                                </h2>
                                <span class="time">[field:pubdate function="MyDate('Y年m月d日 H:i',@me)"/]</span>
                                <div class="xh_post_h_3_entry ofh">[field:description/]</div>
                                <div class="b">
                                     <span title="[field:goodpost/]人赞" class="xh_love"><span class="textcontainer"><span>[field:goodpost/]</span></span> <span class="bartext"></span></span> <span title="[field:click/]人浏览" class="xh_views">[field:click/]</span>
                                </div>
                            </div>
                            <span class="cat"><a href="[field:typeurl/]" title="查看 [field:typename/] 中的全部文章"
                                rel="category tag">[field:typename/]</a></span>
                        </div>