<?php
$z[0]=Array("arcurl","",142,157);
$z[1]=Array("title","",166,180);
$z[2]=Array("litpic","",230,245);
$z[3]=Array("title","",252,266);
$z[4]=Array("arcurl","",483,498);
$z[5]=Array("title","",507,521);
$z[6]=Array("title","",523,537);
$z[7]=Array("pubdate","",633,688);
$z[7][4]['function']="MyDate('YÄêmÔÂdÈÕ H:i',@me)";
$z[8]=Array("description","",764,784);
$z[9]=Array("goodpost","",891,908);
$z[10]=Array("goodpost","",964,981);
$z[11]=Array("click","",1046,1060);
$z[12]=Array("click","",1085,1099);
$z[13]=Array("typeurl","",1239,1255);
$z[14]=Array("typename","",1269,1286);
$z[15]=Array("typename","",1353,1370);

?>