<?php
$z[0]=Array("field","",111,139);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",141,170);
$z[1][4]['name']="typename";
$z[2]=Array("channel","\r\n                    <li class=\"menu-item menu-item-type-taxonomy menu-item-object-category\">\r\n                        <a target=\"_blank\" href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n				",231,480);
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";

?>