<?php
$z[0]=Array("channelartlist","\r\n            <li class=\"menu-item menu-item-type-custom menu-item-object-custom\">\r\n                <a target=\"_blank\" href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n                <ul class=\"sub-menu\">\r\n                {dede:channel type='son' noself='yes'}\r\n                    <li class=\"menu-item menu-item-type-taxonomy menu-item-object-category\">\r\n                        <a target=\"_blank\" href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n				{/dede:channel}\r\n                </ul>\r\n            </li>\r\n",122,716);
$z[0][4]['typeid']="top";

?>