<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('f', arc.flag)>0  And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,4 </font>
Time2016-03-23 14:00:40
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.flash' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.flash
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('a', arc.flag)>0  And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,1 </font>
Time2016-03-23 14:00:40
*/
?>
